#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
"""Preserve licenses from the actual release runtime without importing packages."""
import argparse
import hashlib
import importlib.metadata
import json
import posixpath
from pathlib import Path, PurePosixPath
import re
import shutil
import tarfile
import xml.etree.ElementTree as ET


def write_json(path, value):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, ensure_ascii=False, indent=2) + "\n")


def digest(data):
    return hashlib.sha256(data).hexdigest()


def license_name(name):
    return any(name.lower().startswith(prefix) for prefix in
               ("license", "licence", "copying", "notice", "authors", "copyright"))


def python_licenses(runtime, output, excluded, display_runtime):
    candidates = list((runtime / "lib").glob("python*/site-packages"))
    if len(candidates) != 1:
        raise RuntimeError("The runtime must contain one Python site-packages directory")
    site = candidates[0]
    rows = []
    target_root = output / "python"
    target_root.mkdir(parents=True, exist_ok=True)
    distributions = sorted(importlib.metadata.distributions(path=[str(site)]),
                           key=lambda d: d.metadata["Name"].lower())
    wanted = {f'{d.metadata["Name"]}-{d.version}' for d in distributions
              if d.metadata["Name"].lower() not in excluded}
    # This directory is generated by this utility; remove obsolete snapshots only.
    for directory in target_root.iterdir():
        if directory.is_dir() and directory.name not in wanted:
            shutil.rmtree(directory)
    for distribution in distributions:
        name = distribution.metadata["Name"]
        if name.lower() in excluded:
            continue
        version = distribution.version
        target = target_root / f"{name}-{version}"
        target.mkdir(exist_ok=True)
        shutil.copy2(distribution._path / "METADATA", target / "METADATA")
        files = {}
        for recorded in distribution.files or []:
            if not license_name(PurePosixPath(str(recorded)).name):
                continue
            original = Path(distribution.locate_file(recorded))
            if not original.is_file():
                continue
            relative = Path(*[part for part in PurePosixPath(str(recorded)).parts
                              if part not in ("..", ".")])
            destination = target / relative
            destination.parent.mkdir(parents=True, exist_ok=True)
            data = original.read_bytes()
            destination.write_bytes(data)
            files[relative.as_posix()] = digest(data)
        if name.lower() == "nvidia-ml-py":
            original = site / "pynvml.py"
            lines = original.read_text().splitlines(keepends=True)
            header = []
            for line in lines:
                if not line.lstrip().startswith("#"):
                    break
                header.append(line)
            data = "".join(header).encode()
            if not data or b"Redistribution" not in data:
                raise RuntimeError("NVML source has no identifiable license header")
            (target / "pynvml.py-license-header.txt").write_bytes(data)
            files["pynvml.py-license-header.txt"] = digest(data)
        if not files:
            raise RuntimeError(f"No preserved license for {name} {version}")
        metadata = distribution.metadata
        urls = list(metadata.get_all("Project-URL", []))
        if metadata.get("Home-page"):
            urls.append("Home-page, " + metadata["Home-page"])
        rows.append({"name": name, "version": version,
                     "license_metadata": metadata.get("License-Expression") or metadata.get("License") or "",
                     "license_classifiers": [x for x in metadata.get_all("Classifier", [])
                                             if x.startswith("License ::")],
                     "source_urls": urls,
                     "pypi": f"https://pypi.org/project/{name}/{version}/",
                     "preserved_files": files})
    write_json(output / "PYTHON-DISTRIBUTIONS.json",
               {"count": len(rows), "runtime": display_runtime,
                "excluded_from_binary": sorted(excluded), "distributions": rows})
    return rows


def qt_licenses(sdk, sources, output, imageformats_prefix=None):
    qt = output / "qt"
    (qt / "sbom").mkdir(parents=True, exist_ok=True)
    (qt / "extracted").mkdir(parents=True, exist_ok=True)
    records = []
    for module in ("qtbase", "qtsvg", "qtwayland", "qtimageformats"):
        original = sdk / "sbom" / f"{module}-6.8.3.spdx.json"
        if original.is_file():
            for candidate in (sdk / "sbom").glob(f"{module}-6.8.3*spdx*"):
                shutil.copy2(candidate, qt / "sbom" / candidate.name)
            data = json.loads(original.read_text())
            for entry in data.get("hasExtractedLicensingInfos", []):
                filename = module + "-" + re.sub(r"[^A-Za-z0-9_.-]", "_", entry["licenseId"]) + ".txt"
                (qt / "extracted" / filename).write_text(entry["extractedText"] + "\n")
            records.append({"module": module, "version": "6.8.3", "basis": "installed SDK SPDX",
                            "packages": [{k: p.get(k) for k in
                                          ("name", "versionInfo", "licenseDeclared", "licenseConcluded",
                                           "copyrightText", "downloadLocation")}
                                         for p in data.get("packages", [])]})
        else:
            records.append({"module": module, "version": "6.8.3",
                            "basis": "official source archive; no installed SDK SPDX available",
                            "packages": []})
        if module == "qtimageformats" and imageformats_prefix is not None:
            documents = sorted((imageformats_prefix / "sbom").glob("qtimageformats-6.8.3*spdx*"))
            if not documents:
                raise RuntimeError("The Qt ImageFormats build has no preserved SPDX document")
            for document in documents:
                shutil.copy2(document, qt / "sbom" / document.name)
            records[-1]["basis"] = "local build of verified official 6.8.3 source archive; original generated SPDX preserved"
            records[-1]["build_sbom"] = {document.name: digest(document.read_bytes()) for document in documents}
        if sources is None:
            continue
        archive = sources / f"{module}-everywhere-src-6.8.3.tar.xz"
        collected = {}
        with tarfile.open(archive, "r:xz") as tar:
            members = {member.name: member for member in tar.getmembers() if member.isfile()}
            selected = {name for name in members
                        if license_name(PurePosixPath(name).name) or "/LICENSES/" in name}
            for name in members:
                if PurePosixPath(name).name != "qt_attribution.json":
                    continue
                selected.add(name)
                try:
                    attribution = json.loads(tar.extractfile(members[name]).read(), strict=False)
                except (json.JSONDecodeError, UnicodeDecodeError):
                    # Qt's attribution scanner test fixtures include deliberately
                    # malformed JSON. Keep the original fixture; no linked license
                    # can be inferred from invalid data.
                    continue
                for item in attribution if isinstance(attribution, list) else [attribution]:
                    if not isinstance(item, dict):
                        continue
                    license_file = item.get("LicenseFile")
                    if license_file:
                        candidate = posixpath.normpath((PurePosixPath(name).parent / license_file).as_posix())
                        if candidate in members:
                            selected.add(candidate)
            for name in sorted(selected):
                if ".." in PurePosixPath(name).parts:
                    raise RuntimeError("Unsafe member path in official source archive")
                data = tar.extractfile(members[name]).read()
                destination = qt / "source-notices" / name
                destination.parent.mkdir(parents=True, exist_ok=True)
                destination.write_bytes(data)
                collected[name] = digest(data)
            for name, member in members.items():
                if not name.endswith(".xml") or "protocol" not in name:
                    continue
                try:
                    document = ET.fromstring(tar.extractfile(member).read())
                except ET.ParseError:
                    continue
                copyright_element = document.find("copyright")
                if copyright_element is not None and copyright_element.text:
                    text = copyright_element.text.strip() + "\n"
                    destination = qt / "protocol-notices" / (name + ".txt")
                    destination.parent.mkdir(parents=True, exist_ok=True)
                    destination.write_text(text)
        records[-1]["source_archive"] = archive.name
        records[-1]["source_notice_files"] = collected
    write_json(output / "QT-SDK-PACKAGES.json", records)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--runtime", type=Path, required=True)
    parser.add_argument("--output", type=Path, default=Path("packaging/licenses"))
    parser.add_argument("--qt-sdk", type=Path, default=Path.home() / "Qt/6.8.3/gcc_64")
    parser.add_argument("--qt-sources", type=Path)
    parser.add_argument("--qt-imageformats-prefix", type=Path)
    parser.add_argument("--display-runtime", default="/opt/VisionStudio/runtime")
    parser.add_argument("--exclude", action="append", default=["pip"])
    args = parser.parse_args()
    rows = python_licenses(args.runtime, args.output, {x.lower() for x in args.exclude}, args.display_runtime)
    qt_licenses(args.qt_sdk, args.qt_sources, args.output, args.qt_imageformats_prefix)
    print(f"Preserved {len(rows)} shipped Python distributions and Qt license notices")


if __name__ == "__main__":
    main()
