#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
"""Preserve licenses from the actual release runtime without importing packages."""
import argparse
import hashlib
import importlib.metadata
import json
import posixpath
from pathlib import Path, PurePosixPath
import re
import shutil
import tarfile
import xml.etree.ElementTree as ET


def write_json(path, value):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, ensure_ascii=False, indent=2) + "\n")


def digest(data):
    return hashlib.sha256(data).hexdigest()


def license_name(name):
    return any(name.lower().startswith(prefix) for prefix in
               ("license", "licence", "copying", "notice", "authors", "copyright"))


def python_licenses(runtime, output, excluded, display_runtime, netron_source=None):
    candidates = list((runtime / "lib").glob("python*/site-packages"))
    if len(candidates) != 1:
        raise RuntimeError("The runtime must contain one Python site-packages directory")
    site = candidates[0]
    rows = []
    target_root = output / "python"
    target_root.mkdir(parents=True, exist_ok=True)
    distributions = sorted(importlib.metadata.distributions(path=[str(site)]),
                           key=lambda d: d.metadata["Name"].lower())
    wanted = {f'{d.metadata["Name"]}-{d.version}' for d in distributions
              if d.metadata["Name"].lower() not in excluded}
    # This directory is generated by this utility; remove obsolete snapshots only.
    for directory in target_root.iterdir():
        if directory.is_dir() and directory.name not in wanted:
            shutil.rmtree(directory)
    for distribution in distributions:
        name = distribution.metadata["Name"]
        if name.lower() in excluded:
            continue
        version = distribution.version
        target = target_root / f"{name}-{version}"
        target.mkdir(exist_ok=True)
        shutil.copy2(distribution._path / "METADATA", target / "METADATA")
        files = {}
        for recorded in distribution.files or []:
            if not license_name(PurePosixPath(str(recorded)).name):
                continue
            original = Path(distribution.locate_file(recorded))
            if not original.is_file():
                continue
            relative = Path(*[part for part in PurePosixPath(str(recorded)).parts
                              if part not in ("..", ".")])
            destination = target / relative
            destination.parent.mkdir(parents=True, exist_ok=True)
            data = original.read_bytes()
            destination.write_bytes(data)
            files[relative.as_posix()] = digest(data)
        if name.lower() == "nvidia-ml-py":
            original = site / "pynvml.py"
            lines = original.read_text().splitlines(keepends=True)
            header = []
            for line in lines:
                if not line.lstrip().startswith("#"):
                    break
                header.append(line)
            data = "".join(header).encode()
            if not data or b"Redistribution" not in data:
                raise RuntimeError("NVML source has no identifiable license header")
            (target / "pynvml.py-license-header.txt").write_bytes(data)
            files["pynvml.py-license-header.txt"] = digest(data)
        if name.lower() == "netron":
            if version != "9.3.1" or netron_source is None:
                raise RuntimeError("Netron 9.3.1 requires its exact upstream release-tag source archive")
            with tarfile.open(netron_source, "r:gz") as archive:
                prefix = "netron-9.3.1/"
                metadata_source = json.loads(archive.extractfile(prefix + "package.json").read())
                if metadata_source.get("version") != version or metadata_source.get("license") != "MIT":
                    raise RuntimeError("Netron source version/license does not match the installed wheel")
                license_data = archive.extractfile(prefix + "LICENSE").read()
                (target / "LICENSE-upstream.txt").write_bytes(license_data)
                files["LICENSE-upstream.txt"] = digest(license_data)
                notice_root = output / "netron"
                notice_root.mkdir(parents=True, exist_ok=True)
                for relative in ("LICENSE", "package.json", "package-lock.json"):
                    (notice_root / relative).write_bytes(archive.extractfile(prefix + relative).read())
                # The pip frontend ships source/dagre.js, derived from the
                # explicitly named Dagre and Graphlib projects. Electron and
                # the Node development dependency tree are not shipped.
                original_dagre = archive.extractfile(prefix + "source/dagre.js").read()
                installed_dagre = (site / "netron/dagre.js").read_bytes()
                if original_dagre != installed_dagre:
                    raise RuntimeError("Deployed Netron Dagre frontend differs from the matching source tag")
                (notice_root / "dagre-upstream-reference.txt").write_text(
                    "Netron 9.3.1 source/dagre.js identifies these upstream projects:\n"
                    "https://github.com/dagrejs/dagre\nhttps://github.com/dagrejs/graphlib\n"
                    "Their preserved original MIT license notices are adjacent.\n"
                    "Electron/electron-updater and Node build tools in package-lock.json\n"
                    "are build-only metadata and are absent from this pip-based runtime.\n")
                for notice in ("dagre-LICENSE.txt", "graphlib-LICENSE.txt", "THIRD-PARTY-PROVENANCE.json"):
                    if not (notice_root / notice).is_file():
                        raise RuntimeError("Missing Netron frontend third-party notice: " + notice)
        if not files:
            raise RuntimeError(f"No preserved license for {name} {version}")
        metadata = distribution.metadata
        urls = list(metadata.get_all("Project-URL", []))
        if metadata.get("Home-page"):
            urls.append("Home-page, " + metadata["Home-page"])
        rows.append({"name": name, "version": version,
                     "license_metadata": metadata.get("License-Expression") or metadata.get("License") or "",
                     "license_classifiers": [x for x in metadata.get_all("Classifier", [])
                                             if x.startswith("License ::")],
                     "source_urls": urls,
                     "pypi": f"https://pypi.org/project/{name}/{version}/",
                     "preserved_files": files})
    write_json(output / "PYTHON-DISTRIBUTIONS.json",
               {"count": len(rows), "runtime": display_runtime,
                "excluded_from_binary": sorted(excluded), "distributions": rows})
    return rows


def qt_source_notices(archive, qt):
    """Read large Chromium sources sequentially rather than seeking in XZ."""
    originals = {}
    references = set()
    with tarfile.open(archive, "r|xz") as stream:
        for member in stream:
            if not member.isfile():
                continue
            name = member.name
            basename = PurePosixPath(name).name
            selected = (license_name(basename) or "/LICENSES/" in name
                        or basename in {"README.chromium", "README.qt", "qt_attribution.json"})
            protocol = name.endswith(".xml") and "protocol" in name
            if not selected and not protocol:
                continue
            if PurePosixPath(name).is_absolute() or ".." in PurePosixPath(name).parts:
                raise RuntimeError("Unsafe license member path in official source archive")
            data = stream.extractfile(member).read()
            if selected:
                originals[name] = data
            if basename == "README.chromium":
                match = re.search(r"^License File:\s*(.+)$", data.decode("utf-8", "replace"),
                                  flags=re.MULTILINE)
                if match:
                    for value in match.group(1).split(","):
                        references.add(posixpath.normpath((PurePosixPath(name).parent / value.strip()).as_posix()))
            if basename == "qt_attribution.json":
                try:
                    attribution = json.loads(data, strict=False)
                except (json.JSONDecodeError, UnicodeDecodeError):
                    # Attribution scanner fixtures include invalid JSON; keep
                    # the original without inferring a nonexistent license.
                    attribution = []
                for item in attribution if isinstance(attribution, list) else [attribution]:
                    if isinstance(item, dict) and item.get("LicenseFile"):
                        references.add(posixpath.normpath(
                            (PurePosixPath(name).parent / item["LicenseFile"]).as_posix()))
            if protocol:
                try:
                    document = ET.fromstring(data)
                except ET.ParseError:
                    continue
                copyright_element = document.find("copyright")
                if copyright_element is not None and copyright_element.text:
                    destination = qt / "protocol-notices" / (name + ".txt")
                    destination.parent.mkdir(parents=True, exist_ok=True)
                    destination.write_text(copyright_element.text.strip() + "\n")
    remaining = references - originals.keys()
    if remaining:
        with tarfile.open(archive, "r|xz") as stream:
            for member in stream:
                if member.isfile() and member.name in remaining:
                    originals[member.name] = stream.extractfile(member).read()
    collected = {}
    for name, data in sorted(originals.items()):
        if PurePosixPath(name).is_absolute() or ".." in PurePosixPath(name).parts:
            raise RuntimeError("Unsafe license member path in official source archive")
        destination = qt / "source-notices" / name
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_bytes(data)
        collected[name] = digest(data)
    return collected


def qt_licenses(sdk, sources, output, imageformats_prefix=None):
    qt = output / "qt"
    (qt / "sbom").mkdir(parents=True, exist_ok=True)
    (qt / "extracted").mkdir(parents=True, exist_ok=True)
    records = []
    for module in ("qtbase", "qtsvg", "qtwayland", "qtimageformats", "qtdeclarative",
                   "qtwebchannel", "qtpositioning", "qtwebengine"):
        original = sdk / "sbom" / f"{module}-6.8.3.spdx.json"
        if original.is_file():
            for candidate in (sdk / "sbom").glob(f"{module}-6.8.3*spdx*"):
                shutil.copy2(candidate, qt / "sbom" / candidate.name)
            data = json.loads(original.read_text())
            for entry in data.get("hasExtractedLicensingInfos", []):
                filename = module + "-" + re.sub(r"[^A-Za-z0-9_.-]", "_", entry["licenseId"]) + ".txt"
                (qt / "extracted" / filename).write_text(entry["extractedText"] + "\n")
            records.append({"module": module, "version": "6.8.3", "basis": "installed SDK SPDX",
                            "packages": [{k: p.get(k) for k in
                                          ("name", "versionInfo", "licenseDeclared", "licenseConcluded",
                                           "copyrightText", "downloadLocation")}
                                         for p in data.get("packages", [])]})
        else:
            records.append({"module": module, "version": "6.8.3",
                            "basis": "official source archive; no installed SDK SPDX available",
                            "packages": []})
        if module == "qtimageformats" and imageformats_prefix is not None:
            documents = sorted((imageformats_prefix / "sbom").glob("qtimageformats-6.8.3*spdx*"))
            if not documents:
                raise RuntimeError("The Qt ImageFormats build has no preserved SPDX document")
            for document in documents:
                shutil.copy2(document, qt / "sbom" / document.name)
            records[-1]["basis"] = "local build of verified official 6.8.3 source archive; original generated SPDX preserved"
            records[-1]["build_sbom"] = {document.name: digest(document.read_bytes()) for document in documents}
        if sources is None:
            continue
        archive = sources / f"{module}-everywhere-src-6.8.3.tar.xz"
        # SDK SPDX does not enumerate the complete embedded Chromium tree.
        # Preserve its own per-component notices and the paired full source.
        collected = qt_source_notices(archive, qt)
        records[-1]["source_archive"] = archive.name
        records[-1]["source_notice_files"] = collected
    write_json(output / "QT-SDK-PACKAGES.json", records)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--runtime", type=Path, required=True)
    parser.add_argument("--output", type=Path, default=Path("packaging/licenses"))
    parser.add_argument("--qt-sdk", type=Path, default=Path.home() / "Qt/6.8.3/gcc_64")
    parser.add_argument("--qt-sources", type=Path)
    parser.add_argument("--qt-imageformats-prefix", type=Path)
    parser.add_argument("--netron-source", type=Path,
                        help="The unmodified official Netron v9.3.1 release-tag source archive")
    parser.add_argument("--display-runtime", default="/opt/VisionStudio/runtime")
    parser.add_argument("--exclude", action="append", default=["pip"])
    args = parser.parse_args()
    rows = python_licenses(args.runtime, args.output, {x.lower() for x in args.exclude},
                           args.display_runtime, args.netron_source)
    qt_licenses(args.qt_sdk, args.qt_sources, args.output, args.qt_imageformats_prefix)
    print(f"Preserved {len(rows)} shipped Python distributions and Qt license notices")


if __name__ == "__main__":
    main()
